[package]
name = "piper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5"
atty ="0.2.14"
input_conv ="1.2.0"